#ifndef PERIPHERAL_INC_SDEV_H_
#define PERIPHERAL_INC_SDEV_H_

#include <lely/co/sdev.h>

#ifdef __cplusplus
extern "C" {
#endif

// Declares the static device description (Object Dictionary) generated by dcf2c.
extern const struct co_sdev slave_sdev;

#ifdef __cplusplus
}
#endif

#endif // !PERIPHERAL_INC_SDEV_H_
